"""Unit tests SafeTab config validation."""

# Copyright 2024 Tumult Labs
# 
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
# 
#        http://www.apache.org/licenses/LICENSE-2.0
# 
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

import re
import unittest
from typing import Dict, List

import pytest
from parameterized import parameterized

from tmlt.safetab_utils.config_validation import validate_config_values

# pylint: disable=no-self-use


@pytest.mark.usefixtures("spark")
class TestConfigValidation(unittest.TestCase):
    """Parameterized unit tests for config validation."""

    @parameterized.expand(
        [
            (
                {},
                "safetab-p",
                ["US", "PR"],
                "Invalid config: missing required keys {allow_negative_counts,"
                " max_race_codes, privacy_budget_p_level_1_aiannh,"
                " privacy_budget_p_level_1_county, privacy_budget_p_level_1_place,"
                " privacy_budget_p_level_1_pr_county,"
                " privacy_budget_p_level_1_pr_place, privacy_budget_p_level_1_pr_state,"
                " privacy_budget_p_level_1_pr_tract, privacy_budget_p_level_1_state,"
                " privacy_budget_p_level_1_tract, privacy_budget_p_level_1_usa,"
                " privacy_budget_p_level_2_aiannh, privacy_budget_p_level_2_county,"
                " privacy_budget_p_level_2_place, privacy_budget_p_level_2_pr_county,"
                " privacy_budget_p_level_2_pr_place, privacy_budget_p_level_2_pr_state,"
                " privacy_budget_p_level_2_pr_tract, privacy_budget_p_level_2_state,"
                " privacy_budget_p_level_2_tract, privacy_budget_p_level_2_usa,"
                " privacy_budget_p_stage_1_fraction, privacy_defn, reader, run_pr,"
                " run_us, state_filter_us, thresholds_p}.",
            ),
            (
                {},
                "safetab-h",
                ["US", "PR"],
                "Invalid config: missing required keys {allow_negative_counts,"
                " max_race_codes, privacy_budget_h_t3_level_1_aiannh,"
                " privacy_budget_h_t3_level_1_county,"
                " privacy_budget_h_t3_level_1_place,"
                " privacy_budget_h_t3_level_1_pr_county,"
                " privacy_budget_h_t3_level_1_pr_place,"
                " privacy_budget_h_t3_level_1_pr_state,"
                " privacy_budget_h_t3_level_1_pr_tract,"
                " privacy_budget_h_t3_level_1_state, privacy_budget_h_t3_level_1_tract,"
                " privacy_budget_h_t3_level_1_usa, privacy_budget_h_t3_level_2_aiannh,"
                " privacy_budget_h_t3_level_2_county,"
                " privacy_budget_h_t3_level_2_place,"
                " privacy_budget_h_t3_level_2_pr_county,"
                " privacy_budget_h_t3_level_2_pr_place,"
                " privacy_budget_h_t3_level_2_pr_state,"
                " privacy_budget_h_t3_level_2_pr_tract,"
                " privacy_budget_h_t3_level_2_state, privacy_budget_h_t3_level_2_tract,"
                " privacy_budget_h_t3_level_2_usa, privacy_budget_h_t4_level_1_aiannh,"
                " privacy_budget_h_t4_level_1_county,"
                " privacy_budget_h_t4_level_1_place,"
                " privacy_budget_h_t4_level_1_pr_county,"
                " privacy_budget_h_t4_level_1_pr_place,"
                " privacy_budget_h_t4_level_1_pr_state,"
                " privacy_budget_h_t4_level_1_pr_tract,"
                " privacy_budget_h_t4_level_1_state, privacy_budget_h_t4_level_1_tract,"
                " privacy_budget_h_t4_level_1_usa, privacy_budget_h_t4_level_2_aiannh,"
                " privacy_budget_h_t4_level_2_county,"
                " privacy_budget_h_t4_level_2_place,"
                " privacy_budget_h_t4_level_2_pr_county,"
                " privacy_budget_h_t4_level_2_pr_place,"
                " privacy_budget_h_t4_level_2_pr_state,"
                " privacy_budget_h_t4_level_2_pr_tract,"
                " privacy_budget_h_t4_level_2_state, privacy_budget_h_t4_level_2_tract,"
                " privacy_budget_h_t4_level_2_usa, privacy_defn, reader, run_pr,"
                " run_us, state_filter_us, thresholds_h_t3, thresholds_h_t4}",
            ),
            (
                {},
                "random",
                ["US", "PR"],
                "'program' must be 'safetab-p' or 'safetab-h', not 'random'.",
            ),
            (
                {
                    "max_race_codes": 8,
                    "privacy_budget_h_t3_level_1_aiannh": 15,
                    "privacy_budget_h_t3_level_1_county": 15,
                    "privacy_budget_h_t3_level_1_place": 15,
                    "privacy_budget_h_t3_level_1_pr_county": 15,
                    "privacy_budget_h_t3_level_1_pr_place": 15,
                    "privacy_budget_h_t3_level_1_pr_state": 15,
                    "privacy_budget_h_t3_level_1_pr_tract": 15,
                    "privacy_budget_h_t3_level_1_state": 15,
                    "privacy_budget_h_t3_level_1_tract": 15,
                    "privacy_budget_h_t3_level_1_usa": 15,
                    "privacy_budget_h_t3_level_2_aiannh": 15,
                    "privacy_budget_h_t3_level_2_county": 15,
                    "privacy_budget_h_t3_level_2_place": 15,
                    "privacy_budget_h_t3_level_2_pr_county": 15,
                    "privacy_budget_h_t3_level_2_pr_place": 15,
                    "privacy_budget_h_t3_level_2_pr_state": 15,
                    "privacy_budget_h_t3_level_2_pr_tract": 15,
                    "privacy_budget_h_t3_level_2_state": 15,
                    "privacy_budget_h_t3_level_2_tract": 15,
                    "privacy_budget_h_t3_level_2_usa": 15,
                    "privacy_budget_h_t4_level_1_aiannh": 15,
                    "privacy_budget_h_t4_level_1_county": 15,
                    "privacy_budget_h_t4_level_1_place": 15,
                    "privacy_budget_h_t4_level_1_pr_county": 15,
                    "privacy_budget_h_t4_level_1_pr_place": 15,
                    "privacy_budget_h_t4_level_1_pr_state": 15,
                    "privacy_budget_h_t4_level_1_pr_tract": 15,
                    "privacy_budget_h_t4_level_1_state": 15,
                    "privacy_budget_h_t4_level_1_tract": 15,
                    "privacy_budget_h_t4_level_1_usa": 15,
                    "privacy_budget_h_t4_level_2_aiannh": 15,
                    "privacy_budget_h_t4_level_2_county": 15,
                    "privacy_budget_h_t4_level_2_place": 15,
                    "privacy_budget_h_t4_level_2_pr_county": 15,
                    "privacy_budget_h_t4_level_2_pr_place": 15,
                    "privacy_budget_h_t4_level_2_pr_state": 15,
                    "privacy_budget_h_t4_level_2_pr_tract": 15,
                    "privacy_budget_h_t4_level_2_state": 15,
                    "privacy_budget_h_t4_level_2_tract": 15,
                    "privacy_budget_h_t4_level_2_usa": 15,
                    "thresholds_h_t3": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 5000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "thresholds_h_t4": {
                        "(USA, 1)": [5000],
                        "(USA, 2)": [500],
                        "(STATE, 1)": [5000],
                        "(STATE, 2)": [500],
                        "(COUNTY, 1)": [5000],
                        "(COUNTY, 2)": [1000],
                        "(TRACT, 1)": [5000],
                        "(TRACT, 2)": [1000],
                        "(PLACE, 1)": [5000],
                        "(PLACE, 2)": [1000],
                        "(AIANNH, 1)": [5000],
                        "(AIANNH, 2)": [1000],
                        "(PR-STATE, 1)": [5000],
                        "(PR-STATE, 2)": [500],
                        "(PR-COUNTY, 1)": [5000],
                        "(PR-COUNTY, 2)": [1000],
                        "(PR-TRACT, 1)": [1000],
                        "(PR-TRACT, 2)": [1000],
                        "(PR-PLACE, 1)": [1000],
                        "(PR-PLACE, 2)": [1000],
                    },
                    "allow_negative_counts": True,
                    "run_us": True,
                    "run_pr": False,
                    "reader": "csv",
                    "state_filter_us": ["01", "02", "11"],
                    "privacy_defn": "puredp",
                },
                "safetab-h",
                [],
                "'us_or_puerto_rico_values' must be 'US' and/or 'PR', not '[]'.",
            ),
            (
                {
                    "max_race_codes": 8,
                    "privacy_budget_h_t3_level_1_aiannh": 15,
                    "privacy_budget_h_t3_level_1_county": 15,
                    "privacy_budget_h_t3_level_1_place": 15,
                    "privacy_budget_h_t3_level_1_pr_county": 15,
                    "privacy_budget_h_t3_level_1_pr_place": 15,
                    "privacy_budget_h_t3_level_1_pr_state": 15,
                    "privacy_budget_h_t3_level_1_pr_tract": 15,
                    "privacy_budget_h_t3_level_1_state": 15,
                    "privacy_budget_h_t3_level_1_tract": 15,
                    "privacy_budget_h_t3_level_1_usa": 15,
                    "privacy_budget_h_t3_level_2_aiannh": 15,
                    "privacy_budget_h_t3_level_2_county": 15,
                    "privacy_budget_h_t3_level_2_place": 15,
                    "privacy_budget_h_t3_level_2_pr_county": 15,
                    "privacy_budget_h_t3_level_2_pr_place": 15,
                    "privacy_budget_h_t3_level_2_pr_state": 15,
                    "privacy_budget_h_t3_level_2_pr_tract": 15,
                    "privacy_budget_h_t3_level_2_state": 15,
                    "privacy_budget_h_t3_level_2_tract": 15,
                    "privacy_budget_h_t3_level_2_usa": 15,
                    "privacy_budget_h_t4_level_1_aiannh": 15,
                    "privacy_budget_h_t4_level_1_county": 15,
                    "privacy_budget_h_t4_level_1_place": 15,
                    "privacy_budget_h_t4_level_1_pr_county": 15,
                    "privacy_budget_h_t4_level_1_pr_place": 15,
                    "privacy_budget_h_t4_level_1_pr_state": 15,
                    "privacy_budget_h_t4_level_1_pr_tract": 15,
                    "privacy_budget_h_t4_level_1_state": 15,
                    "privacy_budget_h_t4_level_1_tract": 15,
                    "privacy_budget_h_t4_level_1_usa": 15,
                    "privacy_budget_h_t4_level_2_aiannh": 15,
                    "privacy_budget_h_t4_level_2_county": 15,
                    "privacy_budget_h_t4_level_2_place": 15,
                    "privacy_budget_h_t4_level_2_pr_county": 15,
                    "privacy_budget_h_t4_level_2_pr_place": 15,
                    "privacy_budget_h_t4_level_2_pr_state": 15,
                    "privacy_budget_h_t4_level_2_pr_tract": 15,
                    "privacy_budget_h_t4_level_2_state": 15,
                    "privacy_budget_h_t4_level_2_tract": 15,
                    "privacy_budget_h_t4_level_2_usa": 15,
                    "thresholds_h_t3": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 5000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "thresholds_h_t4": {
                        "(USA, 1)": [5000],
                        "(USA, 2)": [500],
                        "(STATE, 1)": [5000],
                        "(STATE, 2)": [500],
                        "(COUNTY, 1)": [5000],
                        "(COUNTY, 2)": [1000],
                        "(TRACT, 1)": [5000],
                        "(TRACT, 2)": [1000],
                        "(PLACE, 1)": [5000],
                        "(PLACE, 2)": [1000],
                        "(AIANNH, 1)": [5000],
                        "(AIANNH, 2)": [1000],
                        "(PR-STATE, 1)": [5000],
                        "(PR-STATE, 2)": [500],
                        "(PR-COUNTY, 1)": [5000],
                        "(PR-COUNTY, 2)": [1000],
                        "(PR-TRACT, 1)": [1000],
                        "(PR-TRACT, 2)": [1000],
                        "(PR-PLACE, 1)": [1000],
                        "(PR-PLACE, 2)": [1000],
                    },
                    "allow_negative_counts": True,
                    "run_us": True,
                    "run_pr": False,
                    "reader": "csv",
                    "state_filter_us": ["01", "02", "11"],
                    "privacy_defn": "puredp",
                },
                "safetab-h",
                ["random"],
                "'us_or_puerto_rico_values' must be 'US' and/or 'PR', not"
                " '['random']'.",
            ),
            (
                {
                    "max_race_codes": 8,
                    "privacy_budget_h_t3_level_1_aiannh": 15,
                    "privacy_budget_h_t3_level_1_county": 15,
                    "privacy_budget_h_t3_level_1_place": 15,
                    "privacy_budget_h_t3_level_1_pr_county": 15,
                    "privacy_budget_h_t3_level_1_pr_place": 15,
                    "privacy_budget_h_t3_level_1_pr_state": 15,
                    "privacy_budget_h_t3_level_1_pr_tract": 15,
                    "privacy_budget_h_t3_level_1_state": 15,
                    "privacy_budget_h_t3_level_1_tract": 15,
                    "privacy_budget_h_t3_level_1_usa": 15,
                    "privacy_budget_h_t3_level_2_aiannh": 15,
                    "privacy_budget_h_t3_level_2_county": 15,
                    "privacy_budget_h_t3_level_2_place": 15,
                    "privacy_budget_h_t3_level_2_pr_county": 15,
                    "privacy_budget_h_t3_level_2_pr_place": 15,
                    "privacy_budget_h_t3_level_2_pr_state": 15,
                    "privacy_budget_h_t3_level_2_pr_tract": 15,
                    "privacy_budget_h_t3_level_2_state": 15,
                    "privacy_budget_h_t3_level_2_tract": 15,
                    "privacy_budget_h_t3_level_2_usa": 15,
                    "privacy_budget_h_t4_level_1_aiannh": 15,
                    "privacy_budget_h_t4_level_1_county": 15,
                    "privacy_budget_h_t4_level_1_place": 15,
                    "privacy_budget_h_t4_level_1_pr_county": 15,
                    "privacy_budget_h_t4_level_1_pr_place": 15,
                    "privacy_budget_h_t4_level_1_pr_state": 15,
                    "privacy_budget_h_t4_level_1_pr_tract": 15,
                    "privacy_budget_h_t4_level_1_state": 15,
                    "privacy_budget_h_t4_level_1_tract": 15,
                    "privacy_budget_h_t4_level_1_usa": 15,
                    "privacy_budget_h_t4_level_2_aiannh": 15,
                    "privacy_budget_h_t4_level_2_county": 15,
                    "privacy_budget_h_t4_level_2_place": 15,
                    "privacy_budget_h_t4_level_2_pr_county": 15,
                    "privacy_budget_h_t4_level_2_pr_place": 15,
                    "privacy_budget_h_t4_level_2_pr_state": 15,
                    "privacy_budget_h_t4_level_2_pr_tract": 15,
                    "privacy_budget_h_t4_level_2_state": 15,
                    "privacy_budget_h_t4_level_2_tract": 15,
                    "privacy_budget_h_t4_level_2_usa": 15,
                    "thresholds_h_t3": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 5000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "thresholds_h_t4": {
                        "(USA, 1)": [5000],
                        "(USA, 2)": [500],
                        "(STATE, 1)": [5000],
                        "(STATE, 2)": [500],
                        "(COUNTY, 1)": [5000],
                        "(COUNTY, 2)": [1000],
                        "(TRACT, 1)": [5000],
                        "(TRACT, 2)": [1000],
                        "(PLACE, 1)": [5000],
                        "(PLACE, 2)": [1000],
                        "(AIANNH, 1)": [5000],
                        "(AIANNH, 2)": [1000],
                        "(PR-STATE, 1)": [5000],
                        "(PR-STATE, 2)": [500],
                        "(PR-COUNTY, 1)": [5000],
                        "(PR-COUNTY, 2)": [1000],
                        "(PR-TRACT, 1)": [1000],
                        "(PR-TRACT, 2)": [1000],
                        "(PR-PLACE, 1)": [1000],
                        "(PR-PLACE, 2)": [1000],
                    },
                    "allow_negative_counts": True,
                    "run_us": True,
                    "run_pr": False,
                    "reader": "csv",
                    "state_filter_us": ["01", "02", "11"],
                    "privacy_defn": "random",
                },
                "safetab-h",
                ["US"],
                "Invalid config: Supported privacy definitions are Rho zCDP"
                " (zcdp) and Pure DP (puredp).",
            ),
            (
                {
                    "max_race_codes": 14,
                    "privacy_budget_h_t3_level_1_aiannh": 15,
                    "privacy_budget_h_t3_level_1_county": 15,
                    "privacy_budget_h_t3_level_1_place": 15,
                    "privacy_budget_h_t3_level_1_pr_county": 15,
                    "privacy_budget_h_t3_level_1_pr_place": 15,
                    "privacy_budget_h_t3_level_1_pr_state": 15,
                    "privacy_budget_h_t3_level_1_pr_tract": 15,
                    "privacy_budget_h_t3_level_1_state": 15,
                    "privacy_budget_h_t3_level_1_tract": 15,
                    "privacy_budget_h_t3_level_1_usa": 15,
                    "privacy_budget_h_t3_level_2_aiannh": 15,
                    "privacy_budget_h_t3_level_2_county": 15,
                    "privacy_budget_h_t3_level_2_place": 15,
                    "privacy_budget_h_t3_level_2_pr_county": 15,
                    "privacy_budget_h_t3_level_2_pr_place": 15,
                    "privacy_budget_h_t3_level_2_pr_state": 15,
                    "privacy_budget_h_t3_level_2_pr_tract": 15,
                    "privacy_budget_h_t3_level_2_state": 15,
                    "privacy_budget_h_t3_level_2_tract": 15,
                    "privacy_budget_h_t3_level_2_usa": 15,
                    "privacy_budget_h_t4_level_1_aiannh": 15,
                    "privacy_budget_h_t4_level_1_county": 15,
                    "privacy_budget_h_t4_level_1_place": 15,
                    "privacy_budget_h_t4_level_1_pr_county": 15,
                    "privacy_budget_h_t4_level_1_pr_place": 15,
                    "privacy_budget_h_t4_level_1_pr_state": 15,
                    "privacy_budget_h_t4_level_1_pr_tract": 15,
                    "privacy_budget_h_t4_level_1_state": 15,
                    "privacy_budget_h_t4_level_1_tract": 15,
                    "privacy_budget_h_t4_level_1_usa": 15,
                    "privacy_budget_h_t4_level_2_aiannh": 15,
                    "privacy_budget_h_t4_level_2_county": 15,
                    "privacy_budget_h_t4_level_2_place": 15,
                    "privacy_budget_h_t4_level_2_pr_county": 15,
                    "privacy_budget_h_t4_level_2_pr_place": 15,
                    "privacy_budget_h_t4_level_2_pr_state": 15,
                    "privacy_budget_h_t4_level_2_pr_tract": 15,
                    "privacy_budget_h_t4_level_2_state": 15,
                    "privacy_budget_h_t4_level_2_tract": 15,
                    "privacy_budget_h_t4_level_2_usa": 15,
                    "thresholds_h_t3": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 5000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "thresholds_h_t4": {
                        "(USA, 1)": [5000],
                        "(USA, 2)": [500],
                        "(STATE, 1)": [5000],
                        "(STATE, 2)": [500],
                        "(COUNTY, 1)": [5000],
                        "(COUNTY, 2)": [1000],
                        "(TRACT, 1)": [5000],
                        "(TRACT, 2)": [1000],
                        "(PLACE, 1)": [5000],
                        "(PLACE, 2)": [1000],
                        "(AIANNH, 1)": [5000],
                        "(AIANNH, 2)": [1000],
                        "(PR-STATE, 1)": [5000],
                        "(PR-STATE, 2)": [500],
                        "(PR-COUNTY, 1)": [5000],
                        "(PR-COUNTY, 2)": [1000],
                        "(PR-TRACT, 1)": [1000],
                        "(PR-TRACT, 2)": [1000],
                        "(PR-PLACE, 1)": [1000],
                        "(PR-PLACE, 2)": [1000],
                    },
                    "allow_negative_counts": True,
                    "run_us": True,
                    "run_pr": False,
                    "reader": "csv",
                    "state_filter_us": ["01", "02", "11"],
                    "privacy_defn": "puredp",
                },
                "safetab-h",
                ["US"],
                "Invalid config: expected 'max_race_codes' to have "
                "int value between 1 and 8.",
            ),
            (
                {
                    "max_race_codes": 8,
                    "privacy_budget_h_t3_level_1_aiannh": 15,
                    "privacy_budget_h_t3_level_1_county": 15,
                    "privacy_budget_h_t3_level_1_place": 15,
                    "privacy_budget_h_t3_level_1_pr_county": 15,
                    "privacy_budget_h_t3_level_1_pr_place": 15,
                    "privacy_budget_h_t3_level_1_pr_state": 15,
                    "privacy_budget_h_t3_level_1_pr_tract": 15,
                    "privacy_budget_h_t3_level_1_state": 15,
                    "privacy_budget_h_t3_level_1_tract": 15,
                    "privacy_budget_h_t3_level_1_usa": 15,
                    "privacy_budget_h_t3_level_2_aiannh": 15,
                    "privacy_budget_h_t3_level_2_county": 15,
                    "privacy_budget_h_t3_level_2_place": 15,
                    "privacy_budget_h_t3_level_2_pr_county": 15,
                    "privacy_budget_h_t3_level_2_pr_place": 15,
                    "privacy_budget_h_t3_level_2_pr_state": 15,
                    "privacy_budget_h_t3_level_2_pr_tract": 15,
                    "privacy_budget_h_t3_level_2_state": 15,
                    "privacy_budget_h_t3_level_2_tract": 15,
                    "privacy_budget_h_t3_level_2_usa": 15,
                    "privacy_budget_h_t4_level_1_aiannh": 15,
                    "privacy_budget_h_t4_level_1_county": 15,
                    "privacy_budget_h_t4_level_1_place": 15,
                    "privacy_budget_h_t4_level_1_pr_county": 15,
                    "privacy_budget_h_t4_level_1_pr_place": 15,
                    "privacy_budget_h_t4_level_1_pr_state": 15,
                    "privacy_budget_h_t4_level_1_pr_tract": 15,
                    "privacy_budget_h_t4_level_1_state": 15,
                    "privacy_budget_h_t4_level_1_tract": 15,
                    "privacy_budget_h_t4_level_1_usa": 15,
                    "privacy_budget_h_t4_level_2_aiannh": 15,
                    "privacy_budget_h_t4_level_2_county": 15,
                    "privacy_budget_h_t4_level_2_place": 15,
                    "privacy_budget_h_t4_level_2_pr_county": 15,
                    "privacy_budget_h_t4_level_2_pr_place": 15,
                    "privacy_budget_h_t4_level_2_pr_state": 15,
                    "privacy_budget_h_t4_level_2_pr_tract": 15,
                    "privacy_budget_h_t4_level_2_state": 15,
                    "privacy_budget_h_t4_level_2_tract": 15,
                    "privacy_budget_h_t4_level_2_usa": 15,
                    "thresholds_h_t3": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 5000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "thresholds_h_t4": {
                        "(USA, 1)": [5000],
                        "(USA, 2)": [500],
                        "(STATE, 1)": [5000],
                        "(STATE, 2)": [500],
                        "(COUNTY, 1)": [5000],
                        "(COUNTY, 2)": [1000],
                        "(TRACT, 1)": [5000],
                        "(TRACT, 2)": [1000],
                        "(PLACE, 1)": [5000],
                        "(PLACE, 2)": [1000],
                        "(AIANNH, 1)": [5000],
                        "(AIANNH, 2)": [1000],
                        "(PR-STATE, 1)": [5000],
                        "(PR-STATE, 2)": [500],
                        "(PR-COUNTY, 1)": [5000],
                        "(PR-COUNTY, 2)": [1000],
                        "(PR-TRACT, 1)": [1000],
                        "(PR-TRACT, 2)": [1000],
                        "(PR-PLACE, 1)": [1000],
                        "(PR-PLACE, 2)": [1000],
                    },
                    "allow_negative_counts": True,
                    "run_us": "b",
                    "run_pr": False,
                    "reader": "csv",
                    "state_filter_us": ["01", "02", "11"],
                    "privacy_defn": "puredp",
                },
                "safetab-h",
                ["US"],
                "Invalid config: Supported value for 'run_us' are true and false.",
            ),
            (
                {
                    "max_race_codes": 8,
                    "privacy_budget_h_t3_level_1_aiannh": 8,
                    "privacy_budget_h_t3_level_1_county": 8,
                    "privacy_budget_h_t3_level_1_place": 8,
                    "privacy_budget_h_t3_level_1_pr_county": 8,
                    "privacy_budget_h_t3_level_1_pr_place": 8,
                    "privacy_budget_h_t3_level_1_pr_state": 8,
                    "privacy_budget_h_t3_level_1_pr_tract": 8,
                    "privacy_budget_h_t3_level_1_state": 8,
                    "privacy_budget_h_t3_level_1_tract": 8,
                    "privacy_budget_h_t3_level_1_usa": 8,
                    "privacy_budget_h_t3_level_2_aiannh": 8,
                    "privacy_budget_h_t3_level_2_county": 8,
                    "privacy_budget_h_t3_level_2_place": 8,
                    "privacy_budget_h_t3_level_2_pr_county": 8,
                    "privacy_budget_h_t3_level_2_pr_place": 8,
                    "privacy_budget_h_t3_level_2_pr_state": 8,
                    "privacy_budget_h_t3_level_2_pr_tract": 8,
                    "privacy_budget_h_t3_level_2_state": 8,
                    "privacy_budget_h_t3_level_2_tract": "a",
                    "privacy_budget_h_t3_level_2_usa": 8,
                    "privacy_budget_h_t4_level_1_aiannh": 8,
                    "privacy_budget_h_t4_level_1_county": 8,
                    "privacy_budget_h_t4_level_1_place": 8,
                    "privacy_budget_h_t4_level_1_pr_county": 8,
                    "privacy_budget_h_t4_level_1_pr_place": 8,
                    "privacy_budget_h_t4_level_1_pr_state": 8,
                    "privacy_budget_h_t4_level_1_pr_tract": 8,
                    "privacy_budget_h_t4_level_1_state": 8,
                    "privacy_budget_h_t4_level_1_tract": 8,
                    "privacy_budget_h_t4_level_1_usa": 8,
                    "privacy_budget_h_t4_level_2_aiannh": 8,
                    "privacy_budget_h_t4_level_2_county": 8,
                    "privacy_budget_h_t4_level_2_place": 8,
                    "privacy_budget_h_t4_level_2_pr_county": 8,
                    "privacy_budget_h_t4_level_2_pr_place": 8,
                    "privacy_budget_h_t4_level_2_pr_state": 8,
                    "privacy_budget_h_t4_level_2_pr_tract": 8,
                    "privacy_budget_h_t4_level_2_state": 8,
                    "privacy_budget_h_t4_level_2_tract": 8,
                    "privacy_budget_h_t4_level_2_usa": 8,
                    "thresholds_h_t3": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 5000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "thresholds_h_t4": {
                        "(USA, 1)": [5000],
                        "(USA, 2)": [500],
                        "(STATE, 1)": [5000],
                        "(STATE, 2)": [500],
                        "(COUNTY, 1)": [5000],
                        "(COUNTY, 2)": [1000],
                        "(TRACT, 1)": [5000],
                        "(TRACT, 2)": [1000],
                        "(PLACE, 1)": [5000],
                        "(PLACE, 2)": [1000],
                        "(AIANNH, 1)": [5000],
                        "(AIANNH, 2)": [1000],
                        "(PR-STATE, 1)": [5000],
                        "(PR-STATE, 2)": [500],
                        "(PR-COUNTY, 1)": [5000],
                        "(PR-COUNTY, 2)": [1000],
                        "(PR-TRACT, 1)": [1000],
                        "(PR-TRACT, 2)": [1000],
                        "(PR-PLACE, 1)": [1000],
                        "(PR-PLACE, 2)": [1000],
                    },
                    "allow_negative_counts": True,
                    "run_us": True,
                    "run_pr": False,
                    "reader": "csv",
                    "state_filter_us": ["01", "02", "11"],
                    "privacy_defn": "puredp",
                },
                "safetab-h",
                ["US"],
                "Invalid config: expected 'privacy_budget_h_t3_level_2_tract' key "
                "to have float value, not str.",
            ),
            (
                {
                    "max_race_codes": 8,
                    "privacy_budget_h_t3_level_1_aiannh": -1,
                    "privacy_budget_h_t3_level_1_county": 1,
                    "privacy_budget_h_t3_level_1_place": 1,
                    "privacy_budget_h_t3_level_1_pr_county": 1,
                    "privacy_budget_h_t3_level_1_pr_place": 1,
                    "privacy_budget_h_t3_level_1_pr_state": 1,
                    "privacy_budget_h_t3_level_1_pr_tract": 1,
                    "privacy_budget_h_t3_level_1_state": 1,
                    "privacy_budget_h_t3_level_1_tract": 1,
                    "privacy_budget_h_t3_level_1_usa": 1,
                    "privacy_budget_h_t3_level_2_aiannh": 1,
                    "privacy_budget_h_t3_level_2_county": 1,
                    "privacy_budget_h_t3_level_2_place": 1,
                    "privacy_budget_h_t3_level_2_pr_county": 1,
                    "privacy_budget_h_t3_level_2_pr_place": 1,
                    "privacy_budget_h_t3_level_2_pr_state": 1,
                    "privacy_budget_h_t3_level_2_pr_tract": 1,
                    "privacy_budget_h_t3_level_2_state": 1,
                    "privacy_budget_h_t3_level_2_tract": 1,
                    "privacy_budget_h_t3_level_2_usa": 1,
                    "privacy_budget_h_t4_level_1_aiannh": 1,
                    "privacy_budget_h_t4_level_1_county": 1,
                    "privacy_budget_h_t4_level_1_place": 1,
                    "privacy_budget_h_t4_level_1_pr_county": 1,
                    "privacy_budget_h_t4_level_1_pr_place": 1,
                    "privacy_budget_h_t4_level_1_pr_state": 1,
                    "privacy_budget_h_t4_level_1_pr_tract": 1,
                    "privacy_budget_h_t4_level_1_state": 1,
                    "privacy_budget_h_t4_level_1_tract": 1,
                    "privacy_budget_h_t4_level_1_usa": 1,
                    "privacy_budget_h_t4_level_2_aiannh": 1,
                    "privacy_budget_h_t4_level_2_county": 1,
                    "privacy_budget_h_t4_level_2_place": 1,
                    "privacy_budget_h_t4_level_2_pr_county": 1,
                    "privacy_budget_h_t4_level_2_pr_place": 1,
                    "privacy_budget_h_t4_level_2_pr_state": 1,
                    "privacy_budget_h_t4_level_2_pr_tract": 1,
                    "privacy_budget_h_t4_level_2_state": 1,
                    "privacy_budget_h_t4_level_2_tract": 1,
                    "privacy_budget_h_t4_level_2_usa": 1,
                    "thresholds_h_t3": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 5000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "thresholds_h_t4": {
                        "(USA, 1)": [5000],
                        "(USA, 2)": [500],
                        "(STATE, 1)": [5000],
                        "(STATE, 2)": [500],
                        "(COUNTY, 1)": [5000],
                        "(COUNTY, 2)": [1000],
                        "(TRACT, 1)": [5000],
                        "(TRACT, 2)": [1000],
                        "(PLACE, 1)": [5000],
                        "(PLACE, 2)": [1000],
                        "(AIANNH, 1)": [5000],
                        "(AIANNH, 2)": [1000],
                        "(PR-STATE, 1)": [5000],
                        "(PR-STATE, 2)": [500],
                        "(PR-COUNTY, 1)": [5000],
                        "(PR-COUNTY, 2)": [1000],
                        "(PR-TRACT, 1)": [1000],
                        "(PR-TRACT, 2)": [1000],
                        "(PR-PLACE, 1)": [1000],
                        "(PR-PLACE, 2)": [1000],
                    },
                    "allow_negative_counts": True,
                    "run_us": True,
                    "run_pr": False,
                    "reader": "csv",
                    "state_filter_us": ["01", "02", "11"],
                    "privacy_defn": "puredp",
                },
                "safetab-h",
                ["US"],
                "Invalid config: 'privacy_budget_h_t3_level_1_aiannh' must be"
                " non-negative.",
            ),
            (
                {
                    "max_race_codes": 8,
                    "privacy_budget_h_t3_level_1_aiannh": 1,
                    "privacy_budget_h_t3_level_1_county": 1,
                    "privacy_budget_h_t3_level_1_place": 1,
                    "privacy_budget_h_t3_level_1_pr_county": 1,
                    "privacy_budget_h_t3_level_1_pr_place": 1,
                    "privacy_budget_h_t3_level_1_pr_state": 1,
                    "privacy_budget_h_t3_level_1_pr_tract": 1,
                    "privacy_budget_h_t3_level_1_state": 1,
                    "privacy_budget_h_t3_level_1_tract": 1,
                    "privacy_budget_h_t3_level_1_usa": 1,
                    "privacy_budget_h_t3_level_2_aiannh": 1,
                    "privacy_budget_h_t3_level_2_county": 1,
                    "privacy_budget_h_t3_level_2_place": 1,
                    "privacy_budget_h_t3_level_2_pr_county": 1,
                    "privacy_budget_h_t3_level_2_pr_place": 1,
                    "privacy_budget_h_t3_level_2_pr_state": 1,
                    "privacy_budget_h_t3_level_2_pr_tract": 1,
                    "privacy_budget_h_t3_level_2_state": 1,
                    "privacy_budget_h_t3_level_2_tract": 1,
                    "privacy_budget_h_t3_level_2_usa": 1,
                    "privacy_budget_h_t4_level_1_aiannh": 1,
                    "privacy_budget_h_t4_level_1_county": 1,
                    "privacy_budget_h_t4_level_1_place": 1,
                    "privacy_budget_h_t4_level_1_pr_county": 1,
                    "privacy_budget_h_t4_level_1_pr_place": 1,
                    "privacy_budget_h_t4_level_1_pr_state": 1,
                    "privacy_budget_h_t4_level_1_pr_tract": 1,
                    "privacy_budget_h_t4_level_1_state": 1,
                    "privacy_budget_h_t4_level_1_tract": 1,
                    "privacy_budget_h_t4_level_1_usa": 1,
                    "privacy_budget_h_t4_level_2_aiannh": 1,
                    "privacy_budget_h_t4_level_2_county": 1,
                    "privacy_budget_h_t4_level_2_place": 1,
                    "privacy_budget_h_t4_level_2_pr_county": 1,
                    "privacy_budget_h_t4_level_2_pr_place": 1,
                    "privacy_budget_h_t4_level_2_pr_state": 1,
                    "privacy_budget_h_t4_level_2_pr_tract": 1,
                    "privacy_budget_h_t4_level_2_state": 1,
                    "privacy_budget_h_t4_level_2_tract": 1,
                    "privacy_budget_h_t4_level_2_usa": 1,
                    "thresholds_h_t3": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 50000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "thresholds_h_t4": {
                        "(USA, 1)": [5000],
                        "(USA, 2)": [500],
                        "(STATE, 1)": [5000],
                        "(STATE, 2)": [500],
                        "(COUNTY, 1)": [5000],
                        "(COUNTY, 2)": [1000],
                        "(TRACT, 1)": [5000],
                        "(TRACT, 2)": [1000],
                        "(PLACE, 1)": [5000],
                        "(PLACE, 2)": [1000],
                        "(AIANNH, 1)": [5000],
                        "(AIANNH, 2)": [1000],
                        "(PR-STATE, 1)": [5000],
                        "(PR-STATE, 2)": [500],
                        "(PR-COUNTY, 1)": [5000],
                        "(PR-COUNTY, 2)": [1000],
                        "(PR-TRACT, 1)": [1000],
                        "(PR-TRACT, 2)": [1000],
                        "(PR-PLACE, 1)": [1000],
                        "(PR-PLACE, 2)": [1000],
                    },
                    "allow_negative_counts": True,
                    "run_us": True,
                    "run_pr": False,
                    "reader": "csv",
                    "state_filter_us": ["01", "02", "11"],
                    "privacy_defn": "puredp",
                },
                "safetab-h",
                ["US"],
                "Invalid config: At least three non-decreasing thresholds for t3"
                " (COUNTY, 2) should be specified in 'thresholds_h_t3'.",
            ),
            (
                {
                    "max_race_codes": 8,
                    "privacy_budget_h_t3_level_1_aiannh": 1,
                    "privacy_budget_h_t3_level_1_county": 1,
                    "privacy_budget_h_t3_level_1_place": 1,
                    "privacy_budget_h_t3_level_1_pr_county": 1,
                    "privacy_budget_h_t3_level_1_pr_place": 1,
                    "privacy_budget_h_t3_level_1_pr_state": 1,
                    "privacy_budget_h_t3_level_1_pr_tract": 1,
                    "privacy_budget_h_t3_level_1_state": 1,
                    "privacy_budget_h_t3_level_1_tract": 1,
                    "privacy_budget_h_t3_level_1_usa": 1,
                    "privacy_budget_h_t3_level_2_aiannh": 1,
                    "privacy_budget_h_t3_level_2_county": 1,
                    "privacy_budget_h_t3_level_2_place": 1,
                    "privacy_budget_h_t3_level_2_pr_county": 1,
                    "privacy_budget_h_t3_level_2_pr_place": 1,
                    "privacy_budget_h_t3_level_2_pr_state": 1,
                    "privacy_budget_h_t3_level_2_pr_tract": 1,
                    "privacy_budget_h_t3_level_2_state": 1,
                    "privacy_budget_h_t3_level_2_tract": 1,
                    "privacy_budget_h_t3_level_2_usa": 1,
                    "privacy_budget_h_t4_level_1_aiannh": 1,
                    "privacy_budget_h_t4_level_1_county": 1,
                    "privacy_budget_h_t4_level_1_place": 1,
                    "privacy_budget_h_t4_level_1_pr_county": 1,
                    "privacy_budget_h_t4_level_1_pr_place": 1,
                    "privacy_budget_h_t4_level_1_pr_state": 1,
                    "privacy_budget_h_t4_level_1_pr_tract": 1,
                    "privacy_budget_h_t4_level_1_state": 1,
                    "privacy_budget_h_t4_level_1_tract": 1,
                    "privacy_budget_h_t4_level_1_usa": 1,
                    "privacy_budget_h_t4_level_2_aiannh": 1,
                    "privacy_budget_h_t4_level_2_county": 1,
                    "privacy_budget_h_t4_level_2_place": 1,
                    "privacy_budget_h_t4_level_2_pr_county": 1,
                    "privacy_budget_h_t4_level_2_pr_place": 1,
                    "privacy_budget_h_t4_level_2_pr_state": 1,
                    "privacy_budget_h_t4_level_2_pr_tract": 1,
                    "privacy_budget_h_t4_level_2_state": 1,
                    "privacy_budget_h_t4_level_2_tract": 1,
                    "privacy_budget_h_t4_level_2_usa": 1,
                    "thresholds_h_t3": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 5000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "thresholds_h_t4": {
                        "(USA, 1)": [5000],
                        "(USA, 2)": [500],
                        "(STATE, 1)": [5000],
                        "(STATE, 2)": [500],
                        "(COUNTY, 1)": [5000],
                        "(COUNTY, 2)": [1000],
                        "(TRACT, 1)": [5000],
                        "(TRACT, 2)": [1000],
                        "(PLACE, 1)": [5000],
                        "(PLACE, 2)": [1000],
                        "(AIANNH, 1)": [],  # This should be in the error report.
                        "(AIANNH, 2)": [1000],
                        "(PR-STATE, 1)": [5000],
                        "(PR-STATE, 2)": [500],
                        "(PR-COUNTY, 1)": [5000],
                        "(PR-COUNTY, 2)": [1000],
                        "(PR-TRACT, 1)": [1000],
                        "(PR-TRACT, 2)": [1000],
                        "(PR-PLACE, 1)": [1000],
                        "(PR-PLACE, 2)": [1000],
                    },
                    "allow_negative_counts": True,
                    "run_us": True,
                    "run_pr": False,
                    "reader": "csv",
                    "state_filter_us": ["01", "02", "11"],
                    "privacy_defn": "puredp",
                },
                "safetab-h",
                ["US"],
                "Invalid config: One non-decreasing threshold for t4 (AIANNH,"
                " 1) should be specified in 'thresholds_h_t4'.",
                # This test fails currently.
            ),
            (
                {
                    "max_race_codes": 8,
                    "privacy_budget_h_t3_level_1_aiannh": 0,
                    "privacy_budget_h_t3_level_1_county": 0,
                    "privacy_budget_h_t3_level_1_place": 0,
                    "privacy_budget_h_t3_level_1_pr_county": 0,
                    "privacy_budget_h_t3_level_1_pr_place": 0,
                    "privacy_budget_h_t3_level_1_pr_state": 0,
                    "privacy_budget_h_t3_level_1_pr_tract": 0,
                    "privacy_budget_h_t3_level_1_state": 0,
                    "privacy_budget_h_t3_level_1_tract": 0,
                    "privacy_budget_h_t3_level_1_usa": 0,
                    "privacy_budget_h_t3_level_2_aiannh": 0,
                    "privacy_budget_h_t3_level_2_county": 0,
                    "privacy_budget_h_t3_level_2_place": 0,
                    "privacy_budget_h_t3_level_2_pr_county": 0,
                    "privacy_budget_h_t3_level_2_pr_place": 0,
                    "privacy_budget_h_t3_level_2_pr_state": 0,
                    "privacy_budget_h_t3_level_2_pr_tract": 0,
                    "privacy_budget_h_t3_level_2_state": 0,
                    "privacy_budget_h_t3_level_2_tract": 0,
                    "privacy_budget_h_t3_level_2_usa": 0,
                    "privacy_budget_h_t4_level_1_aiannh": 0,
                    "privacy_budget_h_t4_level_1_county": 0,
                    "privacy_budget_h_t4_level_1_place": 0,
                    "privacy_budget_h_t4_level_1_pr_county": 0,
                    "privacy_budget_h_t4_level_1_pr_place": 0,
                    "privacy_budget_h_t4_level_1_pr_state": 0,
                    "privacy_budget_h_t4_level_1_pr_tract": 0,
                    "privacy_budget_h_t4_level_1_state": 0,
                    "privacy_budget_h_t4_level_1_tract": 0,
                    "privacy_budget_h_t4_level_1_usa": 0,
                    "privacy_budget_h_t4_level_2_aiannh": 0,
                    "privacy_budget_h_t4_level_2_county": 0,
                    "privacy_budget_h_t4_level_2_place": 0,
                    "privacy_budget_h_t4_level_2_pr_county": 0,
                    "privacy_budget_h_t4_level_2_pr_place": 0,
                    "privacy_budget_h_t4_level_2_pr_state": 0,
                    "privacy_budget_h_t4_level_2_pr_tract": 0,
                    "privacy_budget_h_t4_level_2_state": 0,
                    "privacy_budget_h_t4_level_2_tract": 0,
                    "privacy_budget_h_t4_level_2_usa": 0,
                    "thresholds_h_t3": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 5000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "thresholds_h_t4": {
                        "(USA, 1)": [5000],
                        "(USA, 2)": [500],
                        "(STATE, 1)": [5000],
                        "(STATE, 2)": [500],
                        "(COUNTY, 1)": [5000],
                        "(COUNTY, 2)": [1000],
                        "(TRACT, 1)": [5000],
                        "(TRACT, 2)": [1000],
                        "(PLACE, 1)": [5000],
                        "(PLACE, 2)": [1000],
                        "(AIANNH, 1)": [],  # This should be in the error report.
                        "(AIANNH, 2)": [1000],
                        "(PR-STATE, 1)": [5000],
                        "(PR-STATE, 2)": [500],
                        "(PR-COUNTY, 1)": [5000],
                        "(PR-COUNTY, 2)": [1000],
                        "(PR-TRACT, 1)": [1000],
                        "(PR-TRACT, 2)": [1000],
                        "(PR-PLACE, 1)": [1000],
                        "(PR-PLACE, 2)": [1000],
                    },
                    "allow_negative_counts": True,
                    "run_us": True,
                    "run_pr": False,
                    "reader": "csv",
                    "state_filter_us": ["01", "02", "11"],
                    "privacy_defn": "puredp",
                },
                "safetab-h",
                ["US"],
                "Invalid config: at least one query's privacy budget must be > 0.",
                # This test fails currently.
            ),
        ]
    )
    def test_invalid_validate_config_values_inputs(
        self,
        config: Dict,
        program: str,
        us_or_puerto_rico_values: List[str],
        error_msg_regex: str,
    ):
        """validate_config_values errors for invalid input parameters.

        Args:
            config: JSON data to be validated, as a Python dict
            program: Algorithm whose input config needs to be validated
            us_or_puerto_rico_values: Speficies run - US or PR or both
            error_msg_regex: A regular expression to check the error message against
        """
        error_msg_regex = re.escape(error_msg_regex)
        with pytest.raises(ValueError, match=error_msg_regex):
            validate_config_values(config, program, us_or_puerto_rico_values)

    @parameterized.expand(
        [
            (
                {
                    "max_race_codes": 8,
                    "privacy_budget_h_t3_level_1_aiannh": 15,
                    "privacy_budget_h_t3_level_1_county": 15,
                    "privacy_budget_h_t3_level_1_place": 15,
                    "privacy_budget_h_t3_level_1_pr_county": 15,
                    "privacy_budget_h_t3_level_1_pr_place": 15,
                    "privacy_budget_h_t3_level_1_pr_state": 15,
                    "privacy_budget_h_t3_level_1_pr_tract": 15,
                    "privacy_budget_h_t3_level_1_state": 15,
                    "privacy_budget_h_t3_level_1_tract": 15,
                    "privacy_budget_h_t3_level_1_usa": 15,
                    "privacy_budget_h_t3_level_2_aiannh": 15,
                    "privacy_budget_h_t3_level_2_county": 15,
                    "privacy_budget_h_t3_level_2_place": 15,
                    "privacy_budget_h_t3_level_2_pr_county": 15,
                    "privacy_budget_h_t3_level_2_pr_place": 15,
                    "privacy_budget_h_t3_level_2_pr_state": 15,
                    "privacy_budget_h_t3_level_2_pr_tract": 15,
                    "privacy_budget_h_t3_level_2_state": 15,
                    "privacy_budget_h_t3_level_2_tract": 15,
                    "privacy_budget_h_t3_level_2_usa": 15,
                    "privacy_budget_h_t4_level_1_aiannh": 15,
                    "privacy_budget_h_t4_level_1_county": 15,
                    "privacy_budget_h_t4_level_1_place": 15,
                    "privacy_budget_h_t4_level_1_pr_county": 15,
                    "privacy_budget_h_t4_level_1_pr_place": 15,
                    "privacy_budget_h_t4_level_1_pr_state": 15,
                    "privacy_budget_h_t4_level_1_pr_tract": 15,
                    "privacy_budget_h_t4_level_1_state": 15,
                    "privacy_budget_h_t4_level_1_tract": 15,
                    "privacy_budget_h_t4_level_1_usa": 15,
                    "privacy_budget_h_t4_level_2_aiannh": 15,
                    "privacy_budget_h_t4_level_2_county": 15,
                    "privacy_budget_h_t4_level_2_place": 15,
                    "privacy_budget_h_t4_level_2_pr_county": 15,
                    "privacy_budget_h_t4_level_2_pr_place": 15,
                    "privacy_budget_h_t4_level_2_pr_state": 15,
                    "privacy_budget_h_t4_level_2_pr_tract": 15,
                    "privacy_budget_h_t4_level_2_state": 15,
                    "privacy_budget_h_t4_level_2_tract": 15,
                    "privacy_budget_h_t4_level_2_usa": 15,
                    "thresholds_h_t3": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 5000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "thresholds_h_t4": {
                        "(USA, 1)": [5000],
                        "(USA, 2)": [500],
                        "(STATE, 1)": [5000],
                        "(STATE, 2)": [500],
                        "(COUNTY, 1)": [5000],
                        "(COUNTY, 2)": [1000],
                        "(TRACT, 1)": [5000],
                        "(TRACT, 2)": [1000],
                        "(PLACE, 1)": [5000],
                        "(PLACE, 2)": [1000],
                        "(AIANNH, 1)": [5000],
                        "(AIANNH, 2)": [1000],
                        "(PR-STATE, 1)": [5000],
                        "(PR-STATE, 2)": [500],
                        "(PR-COUNTY, 1)": [5000],
                        "(PR-COUNTY, 2)": [1000],
                        "(PR-TRACT, 1)": [1000],
                        "(PR-TRACT, 2)": [1000],
                        "(PR-PLACE, 1)": [1000],
                        "(PR-PLACE, 2)": [1000],
                    },
                    "allow_negative_counts": True,
                    "run_us": True,
                    "run_pr": False,
                    "reader": "csv",
                    "state_filter_us": ["01", "02", "11"],
                    "privacy_defn": "puredp",
                },
                "safetab-h",
                ["US"],
            ),
            (
                {
                    "max_race_codes": 8,
                    "privacy_budget_h_t3_level_1_aiannh": 15,
                    "privacy_budget_h_t3_level_1_county": 15,
                    "privacy_budget_h_t3_level_1_place": 15,
                    "privacy_budget_h_t3_level_1_pr_county": 15,
                    "privacy_budget_h_t3_level_1_pr_place": 15,
                    "privacy_budget_h_t3_level_1_pr_state": 15,
                    "privacy_budget_h_t3_level_1_pr_tract": 15,
                    "privacy_budget_h_t3_level_1_state": 15,
                    "privacy_budget_h_t3_level_1_tract": 15,
                    "privacy_budget_h_t3_level_1_usa": 15,
                    "privacy_budget_h_t3_level_2_aiannh": 15,
                    "privacy_budget_h_t3_level_2_county": 15,
                    "privacy_budget_h_t3_level_2_place": 15,
                    "privacy_budget_h_t3_level_2_pr_county": 15,
                    "privacy_budget_h_t3_level_2_pr_place": 15,
                    "privacy_budget_h_t3_level_2_pr_state": 15,
                    "privacy_budget_h_t3_level_2_pr_tract": 15,
                    "privacy_budget_h_t3_level_2_state": 15,
                    "privacy_budget_h_t3_level_2_tract": 15,
                    "privacy_budget_h_t3_level_2_usa": 15,
                    "privacy_budget_h_t4_level_1_aiannh": 15,
                    "privacy_budget_h_t4_level_1_county": 15,
                    "privacy_budget_h_t4_level_1_place": 15,
                    "privacy_budget_h_t4_level_1_pr_county": 15,
                    "privacy_budget_h_t4_level_1_pr_place": 15,
                    "privacy_budget_h_t4_level_1_pr_state": 15,
                    "privacy_budget_h_t4_level_1_pr_tract": 15,
                    "privacy_budget_h_t4_level_1_state": 15,
                    "privacy_budget_h_t4_level_1_tract": 15,
                    "privacy_budget_h_t4_level_1_usa": 15,
                    "privacy_budget_h_t4_level_2_aiannh": 15,
                    "privacy_budget_h_t4_level_2_county": 15,
                    "privacy_budget_h_t4_level_2_place": 15,
                    "privacy_budget_h_t4_level_2_pr_county": 15,
                    "privacy_budget_h_t4_level_2_pr_place": 15,
                    "privacy_budget_h_t4_level_2_pr_state": 15,
                    "privacy_budget_h_t4_level_2_pr_tract": 15,
                    "privacy_budget_h_t4_level_2_state": 15,
                    "privacy_budget_h_t4_level_2_tract": 15,
                    "privacy_budget_h_t4_level_2_usa": 15,
                    "thresholds_h_t3": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 5000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "thresholds_h_t4": {
                        "(USA, 1)": [5000],
                        "(USA, 2)": [500],
                        "(STATE, 1)": [5000],
                        "(STATE, 2)": [500],
                        "(COUNTY, 1)": [5000],
                        "(COUNTY, 2)": [1000],
                        "(TRACT, 1)": [5000],
                        "(TRACT, 2)": [1000],
                        "(PLACE, 1)": [5000],
                        "(PLACE, 2)": [1000],
                        "(AIANNH, 1)": [5000],
                        "(AIANNH, 2)": [1000],
                        "(PR-STATE, 1)": [5000],
                        "(PR-STATE, 2)": [500],
                        "(PR-COUNTY, 1)": [5000],
                        "(PR-COUNTY, 2)": [1000],
                        "(PR-TRACT, 1)": [1000],
                        "(PR-TRACT, 2)": [1000],
                        "(PR-PLACE, 1)": [1000],
                        "(PR-PLACE, 2)": [1000],
                    },
                    "allow_negative_counts": True,
                    "run_us": False,
                    "run_pr": True,
                    "reader": "csv",
                    "state_filter_us": [],
                    "privacy_defn": "puredp",
                },
                "safetab-h",
                ["PR"],
            ),
            (  # with zero_suppression_chance
                {
                    "max_race_codes": 8,
                    "privacy_budget_p_level_1_usa": 0.008,
                    "privacy_budget_p_level_2_usa": 0.534,
                    "privacy_budget_p_level_1_state": 0.008,
                    "privacy_budget_p_level_2_state": 0.534,
                    "privacy_budget_p_level_1_county": 0.008,
                    "privacy_budget_p_level_2_county": 0.159,
                    "privacy_budget_p_level_1_tract": 0,
                    "privacy_budget_p_level_2_tract": 2.43,
                    "privacy_budget_p_level_1_place": 0,
                    "privacy_budget_p_level_2_place": 2.43,
                    "privacy_budget_p_level_1_aiannh": 0,
                    "privacy_budget_p_level_2_aiannh": 0.159,
                    "privacy_budget_p_level_1_pr_state": 0.008,
                    "privacy_budget_p_level_2_pr_state": 0.534,
                    "privacy_budget_p_level_1_pr_county": 0.008,
                    "privacy_budget_p_level_2_pr_county": 0.159,
                    "privacy_budget_p_level_1_pr_tract": 0.008,
                    "privacy_budget_p_level_2_pr_tract": 0.159,
                    "privacy_budget_p_level_1_pr_place": 0.008,
                    "privacy_budget_p_level_2_pr_place": 0.159,
                    "privacy_budget_p_stage_1_fraction": 0.1,
                    "thresholds_p": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 5000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "zero_suppression_chance": 0,
                    "allow_negative_counts": True,
                    "run_us": True,
                    "run_pr": False,
                    "reader": "csv",
                    "state_filter_us": ["01", "02", "11"],
                    "privacy_defn": "zcdp",
                },
                "safetab-p",
                ["US", "PR"],
            ),
            (  # without zero_suppression_chance
                {
                    "max_race_codes": 8,
                    "privacy_budget_p_level_1_usa": 0.008,
                    "privacy_budget_p_level_2_usa": 0.534,
                    "privacy_budget_p_level_1_state": 0.008,
                    "privacy_budget_p_level_2_state": 0.534,
                    "privacy_budget_p_level_1_county": 0.008,
                    "privacy_budget_p_level_2_county": 0.159,
                    "privacy_budget_p_level_1_tract": 0,
                    "privacy_budget_p_level_2_tract": 2.43,
                    "privacy_budget_p_level_1_place": 0,
                    "privacy_budget_p_level_2_place": 2.43,
                    "privacy_budget_p_level_1_aiannh": 0,
                    "privacy_budget_p_level_2_aiannh": 0.159,
                    "privacy_budget_p_level_1_pr_state": 0.008,
                    "privacy_budget_p_level_2_pr_state": 0.534,
                    "privacy_budget_p_level_1_pr_county": 0.008,
                    "privacy_budget_p_level_2_pr_county": 0.159,
                    "privacy_budget_p_level_1_pr_tract": 0.008,
                    "privacy_budget_p_level_2_pr_tract": 0.159,
                    "privacy_budget_p_level_1_pr_place": 0.008,
                    "privacy_budget_p_level_2_pr_place": 0.159,
                    "privacy_budget_p_stage_1_fraction": 0.1,
                    "thresholds_p": {
                        "(USA, 1)": [5000, 20000, 150000],
                        "(USA, 2)": [500, 1000, 7000],
                        "(STATE, 1)": [5000, 20000, 150000],
                        "(STATE, 2)": [500, 1000, 7000],
                        "(COUNTY, 1)": [5000, 20000, 150000],
                        "(COUNTY, 2)": [1000, 5000, 20000],
                        "(TRACT, 1)": [5000, 20000, 150000],
                        "(TRACT, 2)": [1000, 5000, 20000],
                        "(PLACE, 1)": [5000, 20000, 150000],
                        "(PLACE, 2)": [1000, 5000, 20000],
                        "(AIANNH, 1)": [5000, 20000, 150000],
                        "(AIANNH, 2)": [1000, 5000, 20000],
                        "(PR-STATE, 1)": [5000, 20000, 150000],
                        "(PR-STATE, 2)": [500, 1000, 7000],
                        "(PR-COUNTY, 1)": [5000, 20000, 150000],
                        "(PR-COUNTY, 2)": [1000, 5000, 20000],
                        "(PR-TRACT, 1)": [1000, 5000, 20000],
                        "(PR-TRACT, 2)": [1000, 5000, 20000],
                        "(PR-PLACE, 1)": [1000, 5000, 20000],
                        "(PR-PLACE, 2)": [1000, 5000, 20000],
                    },
                    "allow_negative_counts": True,
                    "run_us": True,
                    "run_pr": False,
                    "reader": "csv",
                    "state_filter_us": ["01", "02", "11"],
                    "privacy_defn": "zcdp",
                },
                "safetab-p",
                ["US", "PR"],
            ),
        ]
    )
    def test_valid_validate_config_values_inputs(
        self, config: Dict, program: str, us_or_puerto_rico_values: List[str]
    ):
        """validate_config_values works for valid input parameters.

        Args:
            config: JSON data to be validated, as a Python dict
            program: Algorithm whose input config needs to be validated
            us_or_puerto_rico_values: Speficies run - US or PR or both
        """
        try:
            validate_config_values(config, program, us_or_puerto_rico_values)
        except ValueError:
            self.fail("validate_config_values() raised ValueError unexpectedly!")
